[2023-12-07 15:11:13,195][__main__][INFO] - Running with args: task=free_generation
[2023-12-07 15:11:13,196][__main__][INFO] - Starting to optimize seq for None
[2023-12-07 15:13:04,919][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmps072q8tm
[2023-12-07 15:13:04,920][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmps072q8tm/_remote_module_non_scriptable.py
[2023-12-07 15:13:05,346][__main__][INFO] - Finished Designer init
[2023-12-07 15:13:05,347][__main__][INFO] - Designing sequence for task: free_generation
[2023-12-07 15:13:09,295][__main__][INFO] - Probability of localization: 3.915396519005299e-06
